= Configuring a server to send and receive proxy requests

**Goal:** Configure the server to handle local authentication and proxy requests to different remote RADIUS servers based on realm suffix.

**Time:** 20-30 minutes

*Files to create / edit:*

- `mods-available/proxy-realm1`
- `mods-available/proxy-realm2`
- `mods-enabled/proxy-realm1` (symlink)
- `mods-enabled/proxy-realm2` (symlink)
- `clients.conf`
- `sites-enabled/default`

== Overview

This guide shows how to:

* Authenticate `bob` locally using the `files` module
* Proxy `bob@realm1.com` to remote server 1
* Proxy `bob@realm2.com` to remote server 2

For this exercise, the users will be divided into groups of two using `realm` they use. One
realms will be named "realm1" and the other will be named "realm2".

We assume two remote servers exist with IP addresses you will replace in the `clients.conf` configuration.


User 1:

realm1 is local

realm2 gets proxied to the server running as "realm2".

User 2:

realm1 gets proxied to the server running as "realm1".

realm2 is local

The users should also configure each other's server as a RADIUS
client, as given in the exercise in xref:new_client.adoc[New Clients].

The entry from the exercise in xref:new_user.adoc[New User] for user "bob" in
the file, will be used in this exercise.

The example packets `bob.sh`, `bob@realm1.sh`, and `bob@realm2.sh` may
be used in this exercise.

Each user should test that authentication requests from "bob" to
their RADIUS server should result in authentication accept replies and
that the request was not forwarded to the other RADIUS server.

Each user should test that authentication requests for their own
realm (User 1: "bob@realm1", User 2: "bob@realm2") to their
RADIUS server should result in authentication accept replies and that
the request was not forwarded to the other RADIUS server.

Each user in turn should then attempt authentication using the other
user's realm (User 1: "bob@realm2", User 2: "bob@realm1"),
to their local RADIUS server.

Each in turn should verify that authentication requests for their
realm sent to the other user's RADIUS server results in an
authentication reject.

<<<<<<< HEAD
User 2 should then stop his server. User 1 should then attempt an
authentication request to his server where the request would normally
be proxied. Both users should examine the debug logs of User 1's
RADIUS client and server in order to observe what the server's resulting behaviour
will be.
=======
== Testing Commands

Run server in debug mode:

[source,bash]
----
$ radiusd -X
----

All radclient tests below assume secret = `testing123`

=== Test 1 – Local user (no realm)

[source,bash]
----
echo 'User-Name = "bob", User-Password = "hello"' | radclient -x 127.0.0.1 auth testing123
----

Radclient output :

[source,text]
----
Sent Access-Request Id 200 from 0.0.0.0:58423 to 127.0.0.1:1812 length 61
  Message-Authenticator = 0x
        User-Name = "bob"
        User-Password = "hello"
Received Access-Accept Id 200 from 127.0.0.1:1812 to 0.0.0.0:58423 via lo length 43
        Message-Authenticator = 0x31d0d6a1aba5a83a6d77b4187c0562a5
        User-Name = "bob"
----

Server debug output (main / proxy server – local user) :

[source,text]
----
(0)      if (User-Name =~ /@realm1\.com$/)  {
(0)        | =~
(0)            | User-Name
(0)              | %{User-Name}
(0)              | --> bob
(0)        | ({bob} =~ (null))
(0)        | --> false
(0)        ...
(0)      }
(0)      else {
(0)          files - | ||
(0)          files - | %logical_or()
(0)            files - | Stripped-User-Name
(0)              files - | %{Stripped-User-Name}
(0)              files - (null)
(0)            files - | User-Name
(0)            files - | %logical_or(...)
(0)              files - | %{User-Name}
(0)              files - | --> bob
(0)            files - | %logical_or(...)
(0)            files - | --> bob
(0)        files - files - Looking for key "bob"
(0)        files - files - Found match "bob" on line 1 of ../mods-config/files/authorize
(0)        files - files - Preparing attribute updates:
(0)          files - Password.Cleartext := hello
(0)        files (ok)
----

=== Test 2 – Proxy to realm1.com

[source,bash]
----
echo 'User-Name = "bob@realm1.com", User-Password = "hello"' | radclient -x 127.0.0.1 auth testing123
----

Radclient output :

[source,text]
----
Sent Access-Request Id 130 from 0.0.0.0:43437 to 127.0.0.1:1812 length 72
  Message-Authenticator = 0x
        User-Name = "bob@realm1.com"
        User-Password = "hello"
Received Access-Accept Id 130 from 127.0.0.1:1812 to 0.0.0.0:43437 via lo length 54
        Message-Authenticator = 0x591568951632aae69f913f707912e464
        User-Name = "bob@realm1.com"
----

Server debug output (main / proxy server – proxied user) : 

[source,text]
----
(0)      if (User-Name =~ /@realm1\.com$/)  {
(0)        | =~
(0)            | User-Name
(0)              | %{User-Name}
(0)              | --> bob@realm1.com
(0)        | ({bob@realm1.com} =~ (null))
(0)        | --> true
(0)        proxy-realm1 - proxy-realm1 - [1] Trunk connection assigned request 1
(0)        proxy-realm1 - Sending Access-Request ID 0 length 0 over connection proto udp local 10.0.16.96 port 37726 remote 44.222.160.231 port 1812
(0)          proxy-realm1 - Message-Authenticator = 0xb8c474a818edf42917887303b3181172
(0)          proxy-realm1 - User-Name = "bob@realm1.com"
(0)          proxy-realm1 - User-Password = "hello"
(0)          proxy-realm1 - Packet {
(0)            proxy-realm1 - Id = 130
(0)            proxy-realm1 - Authenticator = 0x970cd7fde6e8fefc4d155017d1a0bed1
(0)          proxy-realm1 - }
(0)          proxy-realm1 - Packet-Type = ::Access-Request
(0)          proxy-realm1 - Proxy-State = 0x6836cf35495baced
(0)        proxy-realm1 - Proxied request.  Relying on NAS to perform more retransmissions
(0)        proxy-realm1 - Received Access-Accept ID 0 length 48 reply packet on connection proto udp local 10.0.16.96 port 37726 remote 44.222.160.231 port 1812
(0)          proxy-realm1 - Message-Authenticator = 0xb0438c94e081c9c66b194a770b38bd5f
(0)          proxy-realm1 - Proxy-State = 0xedac5b4935cf3668
(0)        proxy-realm1 - proxy-realm1 - Resuming execution
(0)        proxy-realm1 (ok)
----

Proxy server debug output (when proxied packet arrives) :

[source,text]
----
(0) suffix: Checking for suffix after "@"
(0) suffix: Looking up realm "realm1.com" for User-Name = "bob@realm1.com"
(0) suffix: Found realm "default"
(0) suffix: Adding Stripped-User-Name = "bob"
(0) suffix: Adding Realm = "default"
(0) suffix: Authentication realm is LOCAL
(0)     [suffix] = ok
(0) files: users: Matched entry bob at line 2
(0)     [files] = ok
(0)     [pap] = updated
(0)   } # authorize = updated
(0) Found Auth-Type = PAP
(0) # Executing group from file ../sites-enabled/default
(0)   Auth-Type PAP {
(0)     [ok] = ok
(0)   } # Auth-Type PAP = ok
----

=== Test 3 – Proxy to realm2.com

[source,text]
----
echo 'User-Name = "bob@realm2.com", User-Password = "hello"' | radclient -x 127.0.0.1 auth testing123
----

Radclient output : 

[source,text]
----
Sent Access-Request Id 130 from 0.0.0.0:43437 to 127.0.0.1:1812 length 72
  Message-Authenticator = 0x
        User-Name = "bob@realm2.com"
        User-Password = "hello"
Received Access-Accept Id 130 from 127.0.0.1:1812 to 0.0.0.0:43437 via lo length 54
        Message-Authenticator = 0x591568951632aae69f913f707912e464
        User-Name = "bob@realm2.com"
----

Server debug output (main / proxy server – proxied user) :

[source,text]
----
(0)      if (User-Name =~ /@realm2\.com$/)  {
(0)        | =~
(0)            | User-Name
(0)              | %{User-Name}
(0)              | --> bob@realm2.com
(0)        | ({bob@realm2.com} =~ (null))
(0)        | --> true
(0)        proxy-realm2 - proxy-realm2 - [1] Trunk connection assigned request 1
(0)        proxy-realm2 - Sending Access-Request ID 0 length 0 over connection proto udp local 10.0.16.96 port 37726 remote 44.222.160.231 port 1812
(0)          proxy-realm2 - Message-Authenticator = 0xb8c474a818edf42917887303b3181172
(0)          proxy-realm2 - User-Name = "bob@realm2.com"
(0)          proxy-realm2 - User-Password = "hello"
(0)          proxy-realm2 - Packet {
(0)            proxy-realm2 - Id = 130
(0)            proxy-realm2 - Authenticator = 0x970cd7fde6e8fefc4d155017d1a0bed1
(0)          proxy-realm2 - }
(0)          proxy-realm2 - Packet-Type = ::Access-Request
(0)          proxy-realm2 - Proxy-State = 0x6836cf35495baced
(0)        proxy-realm2 - Proxied request.  Relying on NAS to perform more retransmissions
(0)        proxy-realm2 - Received Access-Accept ID 0 length 48 reply packet on connection proto udp local 10.0.16.96 port 37726 remote 44.222.160.231 port 1812
(0)          proxy-realm2 - Message-Authenticator = 0xb0438c94e081c9c66b194a770b38bd5f
(0)          proxy-realm2 - Proxy-State = 0xedac5b4935cf3668
(0)        proxy-realm2 - proxy-realm2 - Resuming execution
(0)        proxy-realm2 (ok)
----

Proxy server debug output (when proxied packet arrives) :

[source,text]
----
(0) suffix: Checking for suffix after "@"
(0) suffix: Looking up realm "realm2.com" for User-Name = "bob@realm2.com"
(0) suffix: Found realm "default"
(0) suffix: Adding Stripped-User-Name = "bob"
(0) suffix: Adding Realm = "default"
(0) suffix: Authentication realm is LOCAL
(0)     [suffix] = ok
(0) files: users: Matched entry bob at line 2
(0)     [files] = ok
(0)     [pap] = updated
(0)   } # authorize = updated
(0) Found Auth-Type = PAP
(0) # Executing group from file ../sites-enabled/default
(0)   Auth-Type PAP {
(0)     [ok] = ok
(0)   } # Auth-Type PAP = ok
----

=== Test 4 – Proxy failure simulation

Stop the remote server for realm1, then run :

[source,text]
----
echo 'User-Name = "bob@realm1.com", User-Password = "hello"' | radclient -x 127.0.0.1 auth testing123
----

The request should be rejected
>>>>>>> 66e5ccd613 (doc: add  testing commands to proxy_recieve tutorial)

== Questions

1.  Why is it necessary for each server to mark some realms as local?
2.  What would happen if each user did not configure the other RADIUS
server in the `clients.conf` file?
3.  What would happen if each user did not configure the realms to
"strip" the realm from the proxied requests?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
